from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .main import DevUser, DutyRoster, GenerateRosterRequest, WeekState


def generate_duty_roster(
    *,
    week_start: str,
    state: WeekState,
    user: DevUser,
    request: GenerateRosterRequest | None = None,
) -> DutyRoster:
    """Build a deliberately trivial duty roster for an entry-level exercise.

    This function is intentionally not a real roster-generation algorithm.
    It is an academic exercise scaffold. The goal is to show where each
    important input lives, how to extract it into a named variable, how to
    construct one assignment object, and how to return a valid roster object.

    Parameters:
        week_start:
            The ISO date string supplied by the API route, for example
            ``"2026-06-22"``. This is path input from the HTTP request. In real
            roster generation, use it to identify the relevant weekly cycle and
            reject mismatches between the URL and persisted state.

        state:
            The in-memory ``WeekState`` object for this weekly cycle. It is the
            main context object for the exercise. It contains the uploaded
            programatsia status, the converted shift schedule, worker exclusion
            requests, the previously generated roster, and operational alerts.

        user:
            The authenticated development user that triggered roster
            generation. The API route already checks that this user is a
            manager before calling this function. Real generation code should
            still keep the manager id for audit records and troubleshooting.

        request:
            The optional request body from ``POST /roster/generate``. It
            currently contains only ``force``. A real implementation would use
            this to decide whether existing draft output may be overwritten.

    Returns:
        A valid ``DutyRoster`` object with one hard-coded assignment. The
        values are intentionally simple so a junior developer can replace each
        line with real scheduling logic one step at a time.
    """
    from .main import DutyRoster, RosterAssignment, now

    # 1. Extract API-level input into clear variables.
    requested_week_start = week_start
    manager_id = user.id
    force_requested = request.force if request is not None else False

    # 2. Extract persisted weekly context into clear variables.
    persisted_week_start = state.week_start
    programatsia_status = state.programatsia.status
    schedule_status = state.schedule.status
    existing_roster_status = state.roster.status

    # 3. Extract schedule data. A real algorithm would iterate all shifts.
    all_shifts = state.schedule.shifts
    first_shift = all_shifts[0] if all_shifts else None
    first_shift_id = first_shift.id if first_shift is not None else "exercise-shift-id"
    first_shift_label = first_shift.label if first_shift is not None else "exercise shift"

    # 4. Extract worker request data. A real algorithm would evaluate all of it.
    all_exclusions = list(state.exclusions.values())
    first_exclusion = all_exclusions[0] if all_exclusions else None
    first_excluded_worker_id = first_exclusion.worker_id if first_exclusion is not None else None
    first_excluded_shift_id = first_exclusion.shift_id if first_exclusion is not None else None

    # 5. Extract alert/context data that may later influence generation.
    all_alerts = list(state.alerts.values())
    open_alerts = [alert for alert in all_alerts if alert.status == "open"]
    open_alert_count = len(open_alerts)

    # 6. Build exactly one assignment with intentionally hard-coded values.
    sample_assignment = RosterAssignment(
        id="exercise-assignment-1",
        shift_id="exercise-shift-id",
        worker_id="user1",
        notes="Academic exercise: replace this hard-coded assignment with real logic.",
    )

    # 7. Build a valid but trivial output object.
    return DutyRoster(
        week_start=persisted_week_start,
        status="ready_for_review",
        generated_at=now(),
        generated_by="manager",
        assignments=[sample_assignment],
        warnings=[
            f"Exercise scaffold used for requested week {requested_week_start}.",
            f"Generated by manager {manager_id}; force={force_requested}.",
            f"Programatsia={programatsia_status}; schedule={schedule_status}; previous roster={existing_roster_status}.",
            f"Example source shift={first_shift_id} ({first_shift_label}).",
            f"Example exclusion worker={first_excluded_worker_id}; shift={first_excluded_shift_id}.",
            f"Open alert count={open_alert_count}.",
        ],
    )
